spring.application.name=Hive_RESTfulWebServices

server.port=2003

#optional
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=DATA BASE CONNECTION
spring.datasource.username=root
spring.datasource.password=YOUR PASSWORD 

spring.jpa.hibernate.ddl-auto=update 

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB



#optional
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
